### ISSUE TITLE
cant run shogiviewer on colab

### ISSUE THREAD

**Issue by sugizo** [tkaneko/miniosl#1]
**environment** 
google colab

**code**
```
!apt update
!apt install -y fonts-noto-cjk
pip install -U miniosl drawsvg cairosvg apng coloredlogs 
!wget -c http://live4.computer-shogi.org/wcsc33/kifu/WCSC33+F7_1-900-5F+dlshogi+Ryfamate+20230505161013.csa -O 20230505161013.csa
!shogiconvert --input 20230505161013.csa --output 20230505161013.sfen
!shogiviewer --sfen 20230505161013.sfen
```

**result**
```
>Traceback (most recent call last):
  File "/usr/local/bin/shogiviewer", line 6, in <module>
    miniosl.utility.curses_viewer.main()
  File "/usr/local/lib/python3.10/dist-packages/miniosl/utility/curses_viewer.py", line 201, in main
    curses.wrapper(TUI(ui, record_set))
  File "/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/miniosl/utility/curses_viewer.py", line 50, in __call__
    curses.curs_set(False)
_curses.error: curs_set() returned ERR
```

best regards

**Comment by tkaneko** [comment]
UI in google colab needs a different implementation from that for terminals.  
Please see UI.ipywidget() in r0.0.11. 
https://colab.research.google.com/drive/1orT32kOR58owC0SfhPdC0yodFdn8h2nX?usp=share_link#scrollTo=GMDoB7t7BCcD
