### ISSUE TITLE
*.kif not supported yet

### ISSUE THREAD

**Issue by sugizo** [tkaneko/miniosl#2]
**environment**
google colab

**code**
```
pip install -U miniosl drawsvg cairosvg apng coloredlogs 
f = open('test.kif', "w")
f.write("""#KIF version=2.0 encoding=UTF-8
開始日時：2016/05/01
場所：81Dojo
持ち時間：0分+10秒
手合割：平手
先手：keitama
後手：icecream
手数----指手---------消費時間--
1   ２六歩(27)   (0:3/0:0:3)
2   ３四歩(33)   (0:1/0:0:1)
3   ７六歩(77)   (0:1/0:0:4)
4   ４四歩(43)   (0:1/0:0:2)
5   ４八銀(39)   (0:1/0:0:5)
6   ４二銀(31)   (0:1/0:0:3)
7   ２五歩(26)   (0:1/0:0:6)
8   ３三角(22)   (0:1/0:0:4)
9   ５六歩(57)   (0:1/0:0:7)
10   ４三銀(42)   (0:1/0:0:5)
11   ６八玉(59)   (0:1/0:0:8)
12   ３二金(41)   (0:1/0:0:6)
13   ７八玉(68)   (0:1/0:0:9)
14   ７二銀(71)   (0:1/0:0:7)
15   ６八銀(79)   (0:1/0:0:10)
16   ６四歩(63)   (0:1/0:0:8)
17   ７七銀(68)   (0:1/0:0:11)
18   ７四歩(73)   (0:1/0:0:9)
19   ７九角(88)   (0:1/0:0:12)
20   ６三銀(72)   (0:1/0:0:10)
21   ２四歩(25)   (0:1/0:0:13)
22   同　歩(23)   (0:1/0:0:11)
23   同　角(79)   (0:1/0:0:14)
24   同　角(33)   (0:1/0:0:12)
25   同　飛(28)   (0:1/0:0:15)
26   ２三歩打   (0:1/0:0:13)
27   ２八飛(24)   (0:1/0:0:16)
28   ８四歩(83)   (0:2/0:0:15)
29   １六歩(17)   (0:1/0:0:17)
30   ７三桂(81)   (0:1/0:0:16)
31   ６八金(69)   (0:1/0:0:18)
32   ５二金(61)   (0:1/0:0:17)
33   ３六歩(37)   (0:1/0:0:19)
34   ６二玉(51)   (0:1/0:0:18)
35   ４六歩(47)   (0:1/0:0:20)
36   ８一飛(82)   (0:1/0:0:19)
37   ４七銀(48)   (0:1/0:0:21)
38   ３三桂(21)   (0:1/0:0:20)
39   ５八金(49)   (0:2/0:0:23)
40   ２一飛(81)   (0:1/0:0:21)
41   ３七桂(29)   (0:1/0:0:24)
42   ２四歩(23)   (0:1/0:0:22)
43   ２九飛(28)   (0:2/0:0:26)
44   ２五歩(24)   (0:1/0:0:23)
45   ２七歩打   (0:1/0:0:27)
46   ５四歩(53)   (0:1/0:0:24)
47   ９六歩(97)   (0:2/0:0:29)
48   ９四歩(93)   (0:1/0:0:25)
49   ６六歩(67)   (0:1/0:0:30)
50   １四歩(13)   (0:3/0:0:28)
51   ６七金(68)   (0:1/0:0:31)
52   ４二金(32)   (0:3/0:0:31)
53   ８六銀(77)   (0:3/0:0:34)
54   ８五歩(84)   (0:1/0:0:32)
55   ７七銀(86)   (0:1/0:0:35)
56   ５三玉(62)   (0:2/0:0:34)
57   ４八金(58)   (0:3/0:0:38)
58   ３二金(42)   (0:1/0:0:35)
59   ６八銀(77)   (0:1/0:0:39)
60   ４二玉(53)   (0:1/0:0:36)
61   ７七桂(89)   (0:2/0:0:41)
62   ８一飛(21)   (0:5/0:0:41)
63   ８九飛(29)   (0:3/0:0:44)
64   ６二金(52)   (0:6/0:0:47)
65   ２五桂(37)   (0:1/0:0:45)
66   同　桂(33)   (0:1/0:0:48)
67   ２六歩(27)   (0:1/0:0:46)
68   ３七角打   (0:1/0:0:49)
69   ３八金(48)   (0:1/0:0:47)
70   ２六角成(37)   (0:2/0:0:51)
71   ２九飛(89)   (0:1/0:0:48)
72   ３七馬(26)   (0:2/0:0:53)
73   ２五飛(29)   (0:2/0:0:50)
74   １九馬(37)   (0:1/0:0:54)
75   ２三歩打   (0:6/0:0:56)
76   ２一香打   (0:3/0:0:57)
77   ２四桂打   (0:3/0:0:59)
78   ２三金(32)   (0:1/0:0:58)
79   ３二角打   (0:2/0:1:1)
80   同　銀(43)   (0:5/0:1:3)
81   投了   (0:1/0:1:2)
""")
f.close()
!shogiconvert --input test.kif --output test.sfen
```

**result**
```
Traceback (most recent call last):
  File "/usr/local/bin/shogiconvert", line 6, in <module>
    miniosl.utility.convert_record.main()
  File "/usr/local/lib/python3.10/dist-packages/miniosl/utility/convert_record.py", line 81, in main
    record_set = load_records(args.input)
  File "/usr/local/lib/python3.10/dist-packages/miniosl/utility/convert_record.py", line 35, in load_records
    raise ValueError('not implemented')
ValueError: not implemented
```

best regards

**Comment by tkaneko** [comment]
r0.0.11 has incorporated a kif parser in the original OSL.  Hope this works!
